-- DEPRECATED: This migration has been replaced by the expand-contract pattern
-- DO NOT EXECUTE - This causes production outages by dropping columns while old code reads them
--
-- Original migration (REVERTED):
-- - Dropped trigger/function on messages
-- - Dropped legacy column on conversations
-- - Dropped sequence on messages
--
-- The new migrations (062, 063) implement the correct expand-contract pattern:
-- - Phase 1 (062): Mark columns as deprecated
-- - Phase 2 (063): Remove columns only after application code is updated
--
-- See migrations/062_deprecate_message_sequence.sql and migrations/063_remove_message_sequence.sql

-- This migration has been deprecated in favor of gradual deprecation (see 062_deprecate_message_sequence.sql)
-- No operations performed here - actual cleanup deferred to expand-contract pattern

-- If this migration was already executed in production, follow emergency rollback procedure:
-- 1. Restore database from backup before this migration was applied
-- 2. Deploy new application version that supports both old and new columns
-- 3. Follow expand-contract pattern for gradual migration
