fn main() -> Result<(), Box<dyn std::error::Error>> {
    // Use shared proto file from backend/proto/services
    tonic_build::configure()
        .build_server(true)
        .build_client(false) // Client generated by grpc-clients library
        .compile(
            &["../proto/services/graph_service.proto"],
            &["../proto/services"],
        )?;
    Ok(())
}
