import Foundation

// MARK: - Invitations Service

/// Manages invitation code system for invite-only registration
/// Handles code generation, validation, sending, and referral tracking
class InvitationsService {
    static let shared = InvitationsService()
    private let client = APIClient.shared

    private init() {}

    // MARK: - Generate Invite Code

    /// Generate a new invitation code
    /// - Parameter expiresInDays: Days until code expires (default: 7)
    /// - Returns: Generated invitation code
    func generateInviteCode(expiresInDays: Int = 7) async throws -> InviteCode {
        struct Request: Codable {
            let expiresInDays: Int

            enum CodingKeys: String, CodingKey {
                case expiresInDays = "expires_in_days"
            }
        }

        let request = Request(expiresInDays: expiresInDays)
        return try await client.request(
            endpoint: APIConfig.Invitations.generate,
            method: "POST",
            body: request
        )
    }

    // MARK: - List Invite Codes

    /// Get list of invitation codes generated by current user
    /// - Parameters:
    ///   - limit: Maximum number of codes to return
    ///   - offset: Pagination offset
    /// - Returns: List of invite codes with pagination info
    func getInviteCodes(limit: Int = 20, offset: Int = 0) async throws -> InviteCodesResponse {
        return try await client.get(
            endpoint: APIConfig.Invitations.list,
            queryParams: [
                "limit": String(limit),
                "offset": String(offset)
            ]
        )
    }

    // MARK: - Invite Statistics

    /// Get invitation statistics for current user
    /// - Returns: Invitation statistics
    func getInviteStats() async throws -> InviteStats {
        return try await client.get(endpoint: APIConfig.Invitations.stats)
    }

    // MARK: - Quota

    /// Get invitation quota for current user
    /// - Returns: Quota information
    func getQuota() async throws -> InviteQuota {
        return try await client.get(endpoint: APIConfig.Invitations.quota)
    }

    // MARK: - Send Invitation

    /// Send invitation via specified channel
    /// - Parameters:
    ///   - channel: Delivery channel (sms, email, link)
    ///   - recipient: Recipient phone or email (required for sms/email)
    ///   - message: Optional custom message
    /// - Returns: Send result with invite code
    func sendInvitation(
        channel: InviteChannel,
        recipient: String? = nil,
        message: String? = nil
    ) async throws -> SendInviteResponse {
        struct Request: Codable {
            let channel: String
            let recipient: String?
            let message: String?
        }

        let request = Request(
            channel: channel.rawValue,
            recipient: recipient,
            message: message
        )

        return try await client.request(
            endpoint: APIConfig.Invitations.send,
            method: "POST",
            body: request
        )
    }

    // MARK: - Validate Code

    /// Validate an invitation code (no authentication required)
    /// - Parameter code: Invitation code to validate
    /// - Returns: Validation result
    func validateCode(_ code: String) async throws -> ValidateCodeResponse {
        return try await client.get(
            endpoint: APIConfig.Invitations.validate,
            queryParams: ["code": code]
        )
    }

    // MARK: - Referrals

    /// Get referral information (who invited you and who you invited)
    /// - Returns: Referral information
    func getReferrals() async throws -> ReferralsResponse {
        return try await client.get(endpoint: APIConfig.Invitations.referrals)
    }
}

// MARK: - Models

/// Invitation code model
struct InviteCode: Codable, Identifiable {
    let id: String
    let code: String
    let status: InviteCodeStatus
    let createdAt: Date
    let expiresAt: Date?
    let redeemedAt: Date?
    let redeemedByUserId: String?

    enum CodingKeys: String, CodingKey {
        case id
        case code
        case status
        case createdAt = "created_at"
        case expiresAt = "expires_at"
        case redeemedAt = "redeemed_at"
        case redeemedByUserId = "redeemed_by_user_id"
    }
}

/// Invite code status
enum InviteCodeStatus: String, Codable {
    case pending = "pending"
    case redeemed = "redeemed"
    case expired = "expired"
    case revoked = "revoked"
}

/// Invite codes list response
struct InviteCodesResponse: Codable {
    let codes: [InviteCode]
    let total: Int
    let hasMore: Bool

    enum CodingKeys: String, CodingKey {
        case codes
        case total
        case hasMore = "has_more"
    }
}

/// Invitation statistics
struct InviteStats: Codable {
    let totalGenerated: Int
    let totalRedeemed: Int
    let totalPending: Int
    let totalExpired: Int

    enum CodingKeys: String, CodingKey {
        case totalGenerated = "total_generated"
        case totalRedeemed = "total_redeemed"
        case totalPending = "total_pending"
        case totalExpired = "total_expired"
    }
}

/// Invitation quota
struct InviteQuota: Codable {
    let totalQuota: Int
    let usedQuota: Int
    let remainingQuota: Int
    let successfulReferrals: Int

    enum CodingKeys: String, CodingKey {
        case totalQuota = "total_quota"
        case usedQuota = "used_quota"
        case remainingQuota = "remaining_quota"
        case successfulReferrals = "successful_referrals"
    }
}

/// Invitation delivery channel
enum InviteChannel: String, Codable {
    case sms = "sms"
    case email = "email"
    case link = "link"
}

/// Send invite response
struct SendInviteResponse: Codable {
    let success: Bool
    let code: String
    let shareUrl: String?
    let message: String?

    enum CodingKeys: String, CodingKey {
        case success
        case code
        case shareUrl = "share_url"
        case message
    }
}

/// Validate code response
struct ValidateCodeResponse: Codable {
    let valid: Bool
    let code: String?
    let expiresAt: Date?
    let message: String?

    enum CodingKeys: String, CodingKey {
        case valid
        case code
        case expiresAt = "expires_at"
        case message
    }
}

/// Referrals response
struct ReferralsResponse: Codable {
    let referrer: ReferralUser?
    let referees: [ReferralUser]

    struct ReferralUser: Codable, Identifiable {
        let id: String
        let username: String
        let displayName: String?
        let avatarUrl: String?
        let joinedAt: Date

        enum CodingKeys: String, CodingKey {
            case id
            case username
            case displayName = "display_name"
            case avatarUrl = "avatar_url"
            case joinedAt = "joined_at"
        }
    }
}
