//! VLM Kafka Event Types
//!
//! Defines the event schemas for VLM-related Kafka messages:
//! - PostCreatedForVLM: Incoming event when a post with images is created
//! - VLMPostAnalyzed: Outgoing event when VLM analysis is complete
//! - ChannelsAutoAssigned: Outgoing event when channels are auto-assigned

use serde::{Deserialize, Serialize};
use uuid::Uuid;

/// Kafka topic names for VLM events
pub mod topics {
    /// Topic for posts that need VLM analysis
    pub const POST_CREATED_FOR_VLM: &str = "vlm.post.created";
    /// Topic for VLM analysis results
    pub const VLM_POST_ANALYZED: &str = "vlm.post.analyzed";
    /// Topic for auto-assigned channels
    pub const CHANNELS_AUTO_ASSIGNED: &str = "vlm.channels.assigned";
    /// Dead letter queue for failed VLM processing
    pub const VLM_DLQ: &str = "vlm.events.dlq";
}

/// Event published when a post with images is created and needs VLM analysis
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct PostCreatedForVLM {
    /// Unique event ID for deduplication
    pub event_id: String,
    /// Post ID to analyze
    pub post_id: Uuid,
    /// Creator user ID
    pub creator_id: Uuid,
    /// CDN URLs of images to analyze
    pub image_urls: Vec<String>,
    /// Whether to auto-assign channels
    pub auto_assign_channels: bool,
    /// Maximum number of tags to generate
    pub max_tags: Option<u32>,
    /// Event timestamp (Unix ms)
    pub timestamp: i64,
    /// Correlation ID for tracing
    pub correlation_id: Option<String>,
}

/// A single tag generated by VLM
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct VLMTag {
    /// The tag text (lowercase, normalized)
    pub tag: String,
    /// Confidence score (0.0 - 1.0)
    pub confidence: f32,
    /// Source of the tag (label, object, web_entity)
    pub source: String,
}

/// A suggested channel based on tag matching
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct VLMChannelSuggestion {
    /// Channel ID
    pub channel_id: Uuid,
    /// Channel name
    pub channel_name: String,
    /// Channel slug
    pub channel_slug: String,
    /// Match confidence (0.0 - 1.0)
    pub confidence: f32,
    /// Tags that matched this channel
    pub matched_tags: Vec<String>,
}

/// Event published when VLM analysis is complete
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct VLMPostAnalyzed {
    /// Unique event ID
    pub event_id: String,
    /// Post ID that was analyzed
    pub post_id: Uuid,
    /// Generated tags
    pub tags: Vec<VLMTag>,
    /// Suggested channels (if auto-assign requested)
    pub channel_suggestions: Vec<VLMChannelSuggestion>,
    /// VLM provider used (e.g., "google_vision")
    pub provider: String,
    /// Processing time in milliseconds
    pub processing_time_ms: i64,
    /// Event timestamp (Unix ms)
    pub timestamp: i64,
    /// Original correlation ID
    pub correlation_id: Option<String>,
}

/// Event published when channels are auto-assigned to a post
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ChannelsAutoAssigned {
    /// Unique event ID
    pub event_id: String,
    /// Post ID
    pub post_id: Uuid,
    /// Assigned channel IDs
    pub channel_ids: Vec<Uuid>,
    /// Assignment source (vlm, user, hybrid)
    pub assignment_source: String,
    /// Event timestamp (Unix ms)
    pub timestamp: i64,
    /// Original correlation ID
    pub correlation_id: Option<String>,
}

/// Wrapper for dead letter queue events
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct VLMDeadLetterEvent {
    /// Original event payload
    pub original_event: serde_json::Value,
    /// Original topic
    pub original_topic: String,
    /// Error message
    pub error: String,
    /// Number of retry attempts
    pub retry_count: u32,
    /// Failure timestamp
    pub failed_at: i64,
}

impl PostCreatedForVLM {
    /// Create a new PostCreatedForVLM event
    pub fn new(post_id: Uuid, creator_id: Uuid, image_urls: Vec<String>) -> Self {
        Self {
            event_id: Uuid::new_v4().to_string(),
            post_id,
            creator_id,
            image_urls,
            auto_assign_channels: true,
            max_tags: None,
            timestamp: chrono::Utc::now().timestamp_millis(),
            correlation_id: None,
        }
    }

    /// Set correlation ID for distributed tracing
    pub fn with_correlation_id(mut self, correlation_id: String) -> Self {
        self.correlation_id = Some(correlation_id);
        self
    }
}

impl VLMPostAnalyzed {
    /// Create a new VLMPostAnalyzed event
    pub fn new(
        post_id: Uuid,
        tags: Vec<VLMTag>,
        channel_suggestions: Vec<VLMChannelSuggestion>,
        processing_time_ms: i64,
    ) -> Self {
        Self {
            event_id: Uuid::new_v4().to_string(),
            post_id,
            tags,
            channel_suggestions,
            provider: "google_vision".to_string(),
            processing_time_ms,
            timestamp: chrono::Utc::now().timestamp_millis(),
            correlation_id: None,
        }
    }

    /// Set correlation ID from original event
    pub fn with_correlation_id(mut self, correlation_id: Option<String>) -> Self {
        self.correlation_id = correlation_id;
        self
    }
}
